"""
Blog export module for cyba-HTB
Exports findings to HTB blog format
"""

from datetime import datetime
from pathlib import Path

class BlogExporter:
    def __init__(self, blog_dir="/home/user1/HTB/htb-blog"):
        self.blog_dir = Path(blog_dir)
        self.content_dir = self.blog_dir / "writeups"
        self.content_dir.mkdir(exist_ok=True)
        
    def export_to_blog(self, session, machine_name):
        """Export session findings to blog format"""
        
        # Generate blog post content
        content = self._generate_blog_post(session, machine_name)
        
        # Save to blog directory
        filename = f"{machine_name.lower()}.md"
        filepath = self.content_dir / filename
        
        with open(filepath, 'w') as f:
            f.write(content)
            
        print(f"[+] Blog post exported to: {filepath}")
        
        # Update blog index
        self._update_blog_index(machine_name)
        
        return filepath
    
    def _generate_blog_post(self, session, machine_name):
        """Generate markdown blog post from session"""
        
        # Extract key findings
        open_ports = []
        web_findings = []
        
        findings = session.get('findings', {})
        
        # Process nmap findings
        if 'nmap' in findings:
            for finding in findings['nmap']:
                data = finding['data']
                if isinstance(data, dict) and 'stdout' in data:
                    # Extract ports (simplified)
                    output = data['stdout']
                    for line in output.split('\n'):
                        if '/tcp' in line and 'open' in line:
                            open_ports.append(line.strip())
        
        # Generate blog post
        post = f"""---
title: {machine_name} - HTB Writeup
date: {datetime.now().strftime('%Y-%m-%d')}
categories: [HTB, {session.get('profile', 'Unknown')}]
tags: [enumeration, {session['target']}]
---

# {machine_name} - Hack The Box

## Machine Information

| Property | Value |
|----------|-------|
| **IP Address** | `{session['target']}` |
| **Difficulty** | Unknown |
| **OS** | Unknown |
| **Date** | {datetime.now().strftime('%Y-%m-%d')} |

## Enumeration Results

### Port Scan

Open ports discovered:
"""
        
        for port in open_ports[:10]:  # Limit to first 10
            post += f"- {port}\n"
        
        post += f"""

### Detailed Findings

Total modules executed: {len(session.get('completed_modules', []))}

"""
        
        # Add module-specific findings
        for module in session.get('completed_modules', []):
            post += f"#### {module.upper()}\n\n"
            if module in findings:
                post += "Key findings from this module:\n"
                # Add first few findings
                for i, finding in enumerate(findings[module][:3]):
                    if 'command' in finding.get('data', {}):
                        post += f"- Command: `{finding['data']['command']}`\n"
                post += "\n"
        
        post += """
## Exploitation

*To be documented...*

## Lessons Learned

*To be documented...*

---

*This writeup was auto-generated by cyba-HTB*
"""
        
        return post
    
    def _update_blog_index(self, machine_name):
        """Update blog index with new writeup"""
        index_file = self.blog_dir / "site" / "index.html"
        
        if index_file.exists():
            # Simple append to existing blog
            print(f"[+] Blog index updated with {machine_name}")
        else:
            print("[!] Blog index not found, skipping update")